import { guard } from './auth.js';
import { get, shell, cards } from './ui.js';

if (guard(['admin'])) {
  shell('Panel de administración', [['Candidatos', 'candidatos.html'], ['Vacantes', 'vacantes.html'], ['Empresas', 'empresas.html'], ['Postulaciones', 'postulaciones.html'], ['Entrevistas', 'entrevistas.html'], ['Tareas', 'tareas.html'], ['Personal contratado', '#contratados'], ['Personal desvinculado', '#despedidos'], ['Actividad semanal', '#actividad']]);
  Promise.all([get('/candidatos'), get('/vacantes?estado=activa'), get('/empresas'), get('/postulaciones'), get('/vacantes'), get('/contratados'), get('/despedidos'), get('/actividad_semanal')]).then(([c, v, e, p, all, hired, dismissed, activity]) => {
    const hours = activity.reduce((sum, x) => sum + +x.horas, 0), percent = Math.min(100, Math.round(hours / 40 * 100)), max = Math.max(...activity.map(x => +x.horas), 8);
    document.querySelector('#content').innerHTML = cards([['Candidatos', c.length], ['Vacantes activas', v.length], ['Empresas', e.length], ['Postulaciones', p.length], ['Contratados', hired.length], ['Desvinculados', dismissed.length]]) + `<div class="admin-grid"><div class="panel" id="actividad"><h2>Actividad laboral semanal</h2><div class="progress-head"><b>${hours} h de 40 h</b><span>${percent}%</span></div><div class="progress"><i style="width:${percent}%"></i></div><div class="weekly-chart">${activity.map(x => `<div><i style="height:${Math.max(4, +x.horas / max * 100)}%" title="${x.horas} horas"></i><span>${x.dia.slice(0,3)}</span></div>`).join('')}</div></div><div class="panel"><h2>Últimas vacantes</h2><table><tr><th>Puesto</th><th>Empresa</th><th>Estado</th></tr>${all.slice(-5).reverse().map(x => `<tr><td>${x.titulo}</td><td>${x.empresa}</td><td>${x.estado}</td></tr>`).join('')}</table></div></div><div class="panel" id="contratados"><h2>Personal contratado</h2><table><tr><th>Nombre</th><th>Cargo</th><th>Empresa</th><th>Ingreso</th></tr>${hired.map(x => `<tr><td>${x.nombre}</td><td>${x.cargo}</td><td>${x.empresa}</td><td>${x.fechaIngreso}</td></tr>`).join('') || '<tr><td colspan="4">Sin registros</td></tr>'}</table></div><div class="panel" id="despedidos"><h2>Personal desvinculado</h2><table><tr><th>Nombre</th><th>Cargo</th><th>Empresa</th><th>Salida</th><th>Motivo</th></tr>${dismissed.map(x => `<tr><td>${x.nombre}</td><td>${x.cargo}</td><td>${x.empresa}</td><td>${x.fechaSalida}</td><td>${x.motivo}</td></tr>`).join('') || '<tr><td colspan="5">Sin registros</td></tr>'}</table></div><div class="panel"><h2>Contacto rápido de postulantes</h2>${p.slice().reverse().slice(0, 5).map(x => { const phone = (c.find(y => +y.id === +x.candidatoId)?.phone || '').replace(/[^+\d]/g, ''); return `<article class="application-row"><div><b>${x.nombre}</b><span>${x.cargo} · ${x.estado}</span></div><div><a class="btn alt" href="mailto:${x.email}?subject=Proceso%20de%20selección">Enviar correo</a> <a class="btn" href="tel:${phone}">Llamar</a></div></article>`; }).join('') || '<p>No hay postulantes para contactar.</p>'}</div>`;
  }).catch(e => document.querySelector('#content').textContent = e.message);
}
